# Generated by Django 4.0.2 on 2022-03-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='tanggal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
