# Generated by Django 4.0.2 on 2022-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pendaftaran_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='hari',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='jam',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
