# Generated by Django 4.0.2 on 2022-03-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pendaftaran_hari_pendaftaran_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='poliklinik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poliklinik'),
        ),
    ]
