# Generated by Django 4.0.2 on 2022-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pendaftaran_poliklinik'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntrianTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
            ],
        ),
    ]
